Select COUNT (*) FROM (

SELECT DISTINCT TKT.PNR_LOCTR_ID AS PNR, 
TKT.PNR_CREATE_DT AS PNRDATE, 
--TKT.REVNUE_ACCT_SLS_OUTLET_ID AS STN, 
TKT.CREATE_AGENT_SINE_CD AS ASINE, 
CUST.PNR_PAX_NM AS PAXNAME, 
CAST(TKT.OPERAT_AIRLN_NUMERC_CD AS VARCHAR(3))||CAST(CPN.TICKET_NBR AS VARCHAR(10))  AS TKTPRIME, 
CPN.COUPON_NBR AS CPN, 
CAST(TKT.OPERAT_AIRLN_NUMERC_CD AS VARCHAR(3))||CAST(CPN.TICKET_ASSOC_NBR AS VARCHAR(10)) AS TKTNO, 
TKT.TICKET_ISSUE_DT AS ISSUE, 
FARE.FARE_BASE_AMT AS USDFARE,
CPN.SEG_DEP_AIRPRT_IATA_CD||CPN.SEG_ARVL_AIRPRT_IATA_CD AS MARKET, 
CPN.SCHD_SEG_BEGIN_LCL_DT AS FLTDATE, 
CPN.OA_OPERAT_IATA_CD AS OPERC, 
SRC.COUPON_PRORTE_AMT AS REV, 
CPN.FARE_BASE_CD AS FBS,
CPN.COUPON_STATUS_CD AS STATUS, 
SRC.TICKET_REVNUE_ACCT_DISCNT_CD AS TKTDSG,
FFT.LYLTY_PGM_OWN_CD as FFP, FFT.LYLTY_ACCT_NBR as AADVANTAGE,
FFT.LYLTY_LEVEL_CD as AADVANTAGE_LVL,
TKT.AGENT_OVRRD_PCC_CD AS BKNG_PCC,
TKT.CREATE_AGENT_SINE_CD AS BKNG_AGT, 
TKT.AGENT_HOME_PCC_CD AS TKTG_PCC/*,
lpad(trim(oreplace(coalesce(strtok(osi.other_spcl_instr_txt,'/',2),substr(r.pnr_remrk_txt,3,8)),' ','')),8,'0') as employee_id_number*/


FROM SBVCR_PROD_PKG.TICKET TKT 
JOIN SBVCR_PROD_PKG.TRAVEL_COUPON CPN 
ON TKT.TICKET_NBR = CPN.TICKET_NBR 
AND TKT.TICKET_ISSUE_DT = CPN.TICKET_ISSUE_DT

JOIN SBVCR_PROD_PKG.PARTY_TICKET_ADLS CUST 
ON CPN.TICKET_NBR = CUST.TICKET_NBR 
AND CPN.TICKET_ISSUE_DT = CUST.TICKET_ISSUE_DT

JOIN SBVCR_PROD_PKG.TICKET_FARE_CONSTRC FARE 
ON CUST.TICKET_NBR = FARE.TICKET_NBR 
AND CUST.TICKET_ISSUE_DT = FARE.TICKET_ISSUE_DT


LEFT JOIN SBVCR_PROD_PKG.TRAVEL_COUPON_REVNUE_PRORTE src 
	 on CPN.ACCT_AIRLN_IATA_CD	   = src.ACCT_AIRLN_IATA_CD 
	and CPN.TICKET_NBR 	   = src.TICKET_NBR 
	and CPN.TICKET_ISSUE_DT = src.TICKET_ISSUE_DT 
	and CPN.ENTLMNT_NBR 		   = src.ENTLMNT_NBR

LEFT JOIN SBPNR_PROD_PKG.PNR_FREQ_TRAVLR FFT 
ON TKT.PNR_LOCTR_ID = FFT.PNR_LOCTR_ID 
AND TKT.PNR_CREATE_DT = FFT.PNR_CREATE_DT 
AND FREQ_TRAVLR_SEQ_ID = 1

left join SBPNR_PROD_PKG.pnr_remrk r
    on tkt.pnr_loctr_id = r.pnr_loctr_id
    and tkt.pnr_create_dt = r.pnr_create_dt
    and r.pnr_remrk_txt like '% AA20 BKNG%' 

left join SBPNR_PROD_PKG_SPII.PNR_OTHER_SPCL_INSTR osi
--join prod_pnr_booking_vws.pnr_other_spcl_instr osi
    on tkt.pnr_loctr_id = osi.pnr_loctr_id
    and tkt.pnr_create_dt =osi.pnr_create_dt
    and osi.other_spcl_instr_txt like '%EMPL/%' 

WHERE TKT.TICKET_ISSUE_DT BETWEEN '2023-01-01' AND '2023-01-31'
            AND SRC.TICKET_REVNUE_ACCT_DISCNT_CD LIKE '%AA20%'
            AND TKT.OPERAT_AIRLN_NUMERC_CD IN ('037','001')
            AND CPN.COUPON_STATUS_CD NOT LIKE '%EXCH%'
            AND CPN.COUPON_STATUS_CD NOT LIKE '%VOID%'
--ORDER BY CAST(TKT.OPERAT_AIRLN_NUMERC_CD AS VARCHAR(3))||CAST(CPN.TICKET_ASSOC_NBR AS VARCHAR(10)), 
--CAST(TKT.OPERAT_AIRLN_NUMERC_CD AS VARCHAR(3))||CAST(CPN.TICKET_NBR AS VARCHAR(10)) 
) asd
